[package]
name = "lttr"
version = "0.1.0"
repository = "https://github.com/pascal-huber/typst-letter-template"
entrypoint = "lttr.typ"
authors = [
  "Pascal Huber <pascal.huber@resolved.ch>",
]
license = "MIT"
description = "Letter template"
exclude = [ "/test", "/examples" ]
